Gist - card 6
dana2002/Exercise-ruby pull request #2
Opened 2020-10-07 17:22 UTC by dana2002

2020-10-07 17:31 UTC, Joelit0 commented on gist_content.rb
> +    @content = nil
Is it necessary to set nil content?

2020-10-07 18:50 UTC, pazcuturi commented on gist_content.rb
> +    # p @data
Can we remove this comment?

2020-10-08 15:16 UTC, pazcuturi approved these changes

2020-10-08 17:54 UTC, Joelit0 commented on gist_content.rb
> +      @data["files"][@filename] = content = {'content' => @content}
Use spaces before and after the {}. Example: { 'Hello' => 'World' }

2020-10-08 17:58 UTC, Joelit0 commented on main.rb
> +        break
Use "break if" for better organization in your code: http://www.java2s.com/Code/Ruby/Statement/Breakif.htm

2020-10-08 17:59 UTC, Joelit0 commented on request.rb
> +    @response = http.request(request)
Why is '@response' an instance variable?

2020-10-08 18:02 UTC, Joelit0 commented on main.rb
> +      intentar_de_nuevo = gets.chomp.capitalize
Maybe you can name your variables in English as there are other variables in English.

2020-10-08 18:04 UTC, Joelit0 commented on main.rb
> +      p "Intentar de nuevo?"
The same comment with the 'put', make your code in English or Spanish but not both

2020-10-08 18:06 UTC, Joelit0 commented on gist_content.rb
> +    if Dir.exist?(@pathname)
Maybe you should use the ternary operator for better organization. 
https://www.rubyguides.com/2019/10/ruby-ternary-operator/

2020-10-13 13:51 UTC, jrgonh requested changes

2020-10-13 13:51 UTC, jrgonh commented on .gitignore
> +.env
Newline at end of file

2020-10-13 17:15 UTC, jrgonh approved these changes

2020-10-13 17:17 UTC, merged